# Generated by Django 4.2.7 on 2023-11-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('RegNo', models.CharField(max_length=255)),
                ('Contact', models.CharField(max_length=255)),
                ('Course', models.CharField(max_length=255)),
                ('Date_Time', models.CharField(max_length=255)),
                ('Destination', models.CharField(max_length=255)),
                ('Purpose', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('Aprove', models.BooleanField(default=False)),
            ],
        ),
    ]
